--------------------------------------------------------
--  File created - Wednesday-May-15-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROFILE_EXPERIENCES
--------------------------------------------------------

  CREATE TABLE "PROFILE_EXPERIENCES" 
   (	"ID" NUMBER(19,0), 
	"USER_ID" NUMBER(19,0), 
	"TITLE" VARCHAR2(100 BYTE), 
	"COMPANY" VARCHAR2(120 BYTE), 
	"STATE_ID" NUMBER(19,0), 
	"CITY_ID" NUMBER(19,0), 
	"DATE_START" TIMESTAMP (6), 
	"DATE_END" TIMESTAMP (6), 
	"IS_CURRENTLY_WORKING" NUMBER(19,0), 
	"DESCRIPTION" CLOB, 
	"CREATED_AT" TIMESTAMP (6), 
	"UPDATED_AT" TIMESTAMP (6), 
	"CITY" VARCHAR2(35 BYTE), 
	"TOTAL_TIME" VARCHAR2(20 BYTE), 
	"COUNTRY_ID" CHAR(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into PROFILE_EXPERIENCES
SET DEFINE OFF;
Insert into PROFILE_EXPERIENCES (ID,USER_ID,TITLE,COMPANY,STATE_ID,CITY_ID,DATE_START,DATE_END,IS_CURRENTLY_WORKING,CREATED_AT,UPDATED_AT,CITY,TOTAL_TIME,COUNTRY_ID) values (1,7,'Doctor','ABC',null,null,null,null,null,null,null,'jhk','3 n?m',null);
Insert into PROFILE_EXPERIENCES (ID,USER_ID,TITLE,COMPANY,STATE_ID,CITY_ID,DATE_START,DATE_END,IS_CURRENTLY_WORKING,CREATED_AT,UPDATED_AT,CITY,TOTAL_TIME,COUNTRY_ID) values (4,4,'this is test','Company Name',42,5909,to_timestamp('17-AUG-18 12.00.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('17-AUG-18 12.00.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),0,to_timestamp('10-AUG-18 09.42.55.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('10-AUG-18 09.42.55.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null);
Insert into PROFILE_EXPERIENCES (ID,USER_ID,TITLE,COMPANY,STATE_ID,CITY_ID,DATE_START,DATE_END,IS_CURRENTLY_WORKING,CREATED_AT,UPDATED_AT,CITY,TOTAL_TIME,COUNTRY_ID) values (5,5,'Web Designer','Amoka Int',2728,31439,to_timestamp('15-DEC-10 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('15-FEB-11 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),0,to_timestamp('30-AUG-18 02.13.07.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('30-AUG-18 02.13.07.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null);
Insert into PROFILE_EXPERIENCES (ID,USER_ID,TITLE,COMPANY,STATE_ID,CITY_ID,DATE_START,DATE_END,IS_CURRENTLY_WORKING,CREATED_AT,UPDATED_AT,CITY,TOTAL_TIME,COUNTRY_ID) values (6,6,'Web Designer','My Test Company 1',3919,42596,to_timestamp('05-JAN-16 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('30-DEC-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),0,to_timestamp('19-SEP-18 08.34.30.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('19-SEP-18 08.34.30.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null);
Insert into PROFILE_EXPERIENCES (ID,USER_ID,TITLE,COMPANY,STATE_ID,CITY_ID,DATE_START,DATE_END,IS_CURRENTLY_WORKING,CREATED_AT,UPDATED_AT,CITY,TOTAL_TIME,COUNTRY_ID) values (7,6,'Senior Frontend Developer','My Test Company 2',3931,43999,to_timestamp('09-JAN-18 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,1,to_timestamp('19-SEP-18 08.35.39.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('19-SEP-18 08.35.39.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null);
Insert into PROFILE_EXPERIENCES (ID,USER_ID,TITLE,COMPANY,STATE_ID,CITY_ID,DATE_START,DATE_END,IS_CURRENTLY_WORKING,CREATED_AT,UPDATED_AT,CITY,TOTAL_TIME,COUNTRY_ID) values (21,101,',mn','Nhom85',null,null,null,null,null,null,null,'Chia','3 nam','CN');
--------------------------------------------------------
--  DDL for Index SYS_C007518
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007518" ON "PROFILE_EXPERIENCES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Trigger TG_ID_PR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "TG_ID_PR" 
  BEFORE INSERT ON PROFILE_EXPERIENCES
  FOR EACH ROW
BEGIN
  SELECT
   ID_PR.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
ALTER TRIGGER "TG_ID_PR" ENABLE;
--------------------------------------------------------
--  Constraints for Table PROFILE_EXPERIENCES
--------------------------------------------------------

  ALTER TABLE "PROFILE_EXPERIENCES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROFILE_EXPERIENCES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
