--------------------------------------------------------
--  File created - Wednesday-May-15-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROFILE_EDUCATIONS
--------------------------------------------------------

  CREATE TABLE "PROFILE_EDUCATIONS" 
   (	"ID" NUMBER(19,0), 
	"USER_ID" NUMBER(19,0), 
	"DEGREE_LEVEL_ID" NUMBER(19,0), 
	"DEGREE_TYPE_ID" NUMBER(19,0), 
	"DEGREE_TITLE" VARCHAR2(150 BYTE), 
	"COUNTRY_ID" NUMBER(19,0), 
	"STATE_ID" NUMBER(19,0), 
	"CITY_ID" NUMBER(19,0), 
	"DATE_COMPLETION" VARCHAR2(15 BYTE), 
	"INSTITUTION" VARCHAR2(150 BYTE), 
	"DEGREE_RESULT" VARCHAR2(20 BYTE), 
	"RESULT_TYPE_ID" NUMBER(19,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"UPDATED_AT" TIMESTAMP (6), 
	"ACADEMIC" VARCHAR2(35 BYTE), 
	"SCHOOLNAME" VARCHAR2(35 BYTE), 
	"MAJOR" VARCHAR2(35 BYTE), 
	"PROCESS" VARCHAR2(35 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
REM INSERTING into PROFILE_EDUCATIONS
SET DEFINE OFF;
Insert into PROFILE_EDUCATIONS (ID,USER_ID,DEGREE_LEVEL_ID,DEGREE_TYPE_ID,DEGREE_TITLE,COUNTRY_ID,STATE_ID,CITY_ID,DATE_COMPLETION,INSTITUTION,DEGREE_RESULT,RESULT_TYPE_ID,CREATED_AT,UPDATED_AT,ACADEMIC,SCHOOLNAME,MAJOR,PROCESS) values (9,5,null,null,null,null,null,null,null,null,null,null,null,null,'College','Dai hoc Can Tho','Math',null);
Insert into PROFILE_EDUCATIONS (ID,USER_ID,DEGREE_LEVEL_ID,DEGREE_TYPE_ID,DEGREE_TITLE,COUNTRY_ID,STATE_ID,CITY_ID,DATE_COMPLETION,INSTITUTION,DEGREE_RESULT,RESULT_TYPE_ID,CREATED_AT,UPDATED_AT,ACADEMIC,SCHOOLNAME,MAJOR,PROCESS) values (1,5,null,null,null,null,null,null,null,null,null,null,null,null,'College','Dai hoc Can Tho','Math',null);
Insert into PROFILE_EDUCATIONS (ID,USER_ID,DEGREE_LEVEL_ID,DEGREE_TYPE_ID,DEGREE_TITLE,COUNTRY_ID,STATE_ID,CITY_ID,DATE_COMPLETION,INSTITUTION,DEGREE_RESULT,RESULT_TYPE_ID,CREATED_AT,UPDATED_AT,ACADEMIC,SCHOOLNAME,MAJOR,PROCESS) values (6,4,5,110,'MCS',166,2728,31351,'2009','VU','65',3,to_timestamp('10-AUG-18 09.44.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('10-AUG-18 09.44.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into PROFILE_EDUCATIONS (ID,USER_ID,DEGREE_LEVEL_ID,DEGREE_TYPE_ID,DEGREE_TITLE,COUNTRY_ID,STATE_ID,CITY_ID,DATE_COMPLETION,INSTITUTION,DEGREE_RESULT,RESULT_TYPE_ID,CREATED_AT,UPDATED_AT,ACADEMIC,SCHOOLNAME,MAJOR,PROCESS) values (7,6,2,2,'Matric',231,3921,42691,'2012','My test Institute','A',2,to_timestamp('19-SEP-18 08.36.57.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('19-SEP-18 08.36.57.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into PROFILE_EDUCATIONS (ID,USER_ID,DEGREE_LEVEL_ID,DEGREE_TYPE_ID,DEGREE_TITLE,COUNTRY_ID,STATE_ID,CITY_ID,DATE_COMPLETION,INSTITUTION,DEGREE_RESULT,RESULT_TYPE_ID,CREATED_AT,UPDATED_AT,ACADEMIC,SCHOOLNAME,MAJOR,PROCESS) values (8,6,3,17,'ICS',231,3924,43230,'2014','My test Institute 2','A',2,to_timestamp('19-SEP-18 08.38.06.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('19-SEP-18 08.38.06.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into PROFILE_EDUCATIONS (ID,USER_ID,DEGREE_LEVEL_ID,DEGREE_TYPE_ID,DEGREE_TITLE,COUNTRY_ID,STATE_ID,CITY_ID,DATE_COMPLETION,INSTITUTION,DEGREE_RESULT,RESULT_TYPE_ID,CREATED_AT,UPDATED_AT,ACADEMIC,SCHOOLNAME,MAJOR,PROCESS) values (21,101,null,null,null,null,null,null,null,null,null,null,null,null,'Junior High School','Ho Chi Minh University of Education','Information Of Technology',null);
Insert into PROFILE_EDUCATIONS (ID,USER_ID,DEGREE_LEVEL_ID,DEGREE_TYPE_ID,DEGREE_TITLE,COUNTRY_ID,STATE_ID,CITY_ID,DATE_COMPLETION,INSTITUTION,DEGREE_RESULT,RESULT_TYPE_ID,CREATED_AT,UPDATED_AT,ACADEMIC,SCHOOLNAME,MAJOR,PROCESS) values (22,101,null,null,null,null,null,null,null,null,null,null,null,null,'Junior High School','Ho Chi Minh University of Education','Information Of Technology',null);
Insert into PROFILE_EDUCATIONS (ID,USER_ID,DEGREE_LEVEL_ID,DEGREE_TYPE_ID,DEGREE_TITLE,COUNTRY_ID,STATE_ID,CITY_ID,DATE_COMPLETION,INSTITUTION,DEGREE_RESULT,RESULT_TYPE_ID,CREATED_AT,UPDATED_AT,ACADEMIC,SCHOOLNAME,MAJOR,PROCESS) values (41,101,null,null,null,null,null,null,null,null,null,null,null,null,'Junior High School','Ho Chi Minh University of Education','Information Of Technology',null);
--------------------------------------------------------
--  DDL for Index SYS_C007516
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007516" ON "PROFILE_EDUCATIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Trigger TG_ID_PROFILE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "TG_ID_PROFILE" 
  BEFORE INSERT ON PROFILE_EDUCATIONS
  FOR EACH ROW
BEGIN
  SELECT
   ID_auto_increare.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
ALTER TRIGGER "TG_ID_PROFILE" ENABLE;
--------------------------------------------------------
--  Constraints for Table PROFILE_EDUCATIONS
--------------------------------------------------------

  ALTER TABLE "PROFILE_EDUCATIONS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROFILE_EDUCATIONS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
