--------------------------------------------------------
--  File created - Wednesday-May-15-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROFILE_LANGUAGES
--------------------------------------------------------

  CREATE TABLE "PROFILE_LANGUAGES" 
   (	"ID" NUMBER(19,0), 
	"USER_ID" NUMBER(19,0), 
	"LANGUAGE_ID" NUMBER(19,0), 
	"LANGUAGE_LEVEL_ID" NUMBER(19,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"UPDATED_AT" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
REM INSERTING into PROFILE_LANGUAGES
SET DEFINE OFF;
Insert into PROFILE_LANGUAGES (ID,USER_ID,LANGUAGE_ID,LANGUAGE_LEVEL_ID,CREATED_AT,UPDATED_AT) values (7,4,13,3,to_timestamp('10-AUG-18 09.45.09.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('10-AUG-18 09.45.09.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into PROFILE_LANGUAGES (ID,USER_ID,LANGUAGE_ID,LANGUAGE_LEVEL_ID,CREATED_AT,UPDATED_AT) values (8,5,179,3,to_timestamp('30-AUG-18 02.14.12.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('30-AUG-18 02.14.12.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into PROFILE_LANGUAGES (ID,USER_ID,LANGUAGE_ID,LANGUAGE_LEVEL_ID,CREATED_AT,UPDATED_AT) values (9,5,44,2,to_timestamp('30-AUG-18 02.14.23.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('30-AUG-18 02.14.23.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into PROFILE_LANGUAGES (ID,USER_ID,LANGUAGE_ID,LANGUAGE_LEVEL_ID,CREATED_AT,UPDATED_AT) values (10,6,44,3,to_timestamp('19-SEP-18 08.39.45.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('19-SEP-18 08.39.45.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into PROFILE_LANGUAGES (ID,USER_ID,LANGUAGE_ID,LANGUAGE_LEVEL_ID,CREATED_AT,UPDATED_AT) values (11,6,174,2,to_timestamp('19-SEP-18 08.39.58.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('19-SEP-18 08.39.58.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into PROFILE_LANGUAGES (ID,USER_ID,LANGUAGE_ID,LANGUAGE_LEVEL_ID,CREATED_AT,UPDATED_AT) values (12,6,8,2,to_timestamp('19-SEP-18 08.40.11.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('19-SEP-18 08.40.11.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into PROFILE_LANGUAGES (ID,USER_ID,LANGUAGE_ID,LANGUAGE_LEVEL_ID,CREATED_AT,UPDATED_AT) values (13,6,31,1,to_timestamp('19-SEP-18 08.40.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('19-SEP-18 08.40.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into PROFILE_LANGUAGES (ID,USER_ID,LANGUAGE_ID,LANGUAGE_LEVEL_ID,CREATED_AT,UPDATED_AT) values (23,101,31,1,null,null);
Insert into PROFILE_LANGUAGES (ID,USER_ID,LANGUAGE_ID,LANGUAGE_LEVEL_ID,CREATED_AT,UPDATED_AT) values (24,101,44,1,null,null);
Insert into PROFILE_LANGUAGES (ID,USER_ID,LANGUAGE_ID,LANGUAGE_LEVEL_ID,CREATED_AT,UPDATED_AT) values (41,101,44,1,null,null);
Insert into PROFILE_LANGUAGES (ID,USER_ID,LANGUAGE_ID,LANGUAGE_LEVEL_ID,CREATED_AT,UPDATED_AT) values (42,101,44,1,null,null);
Insert into PROFILE_LANGUAGES (ID,USER_ID,LANGUAGE_ID,LANGUAGE_LEVEL_ID,CREATED_AT,UPDATED_AT) values (43,101,51,1,null,null);
--------------------------------------------------------
--  DDL for Index SYS_C007520
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007520" ON "PROFILE_LANGUAGES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Trigger TG_PROFILE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "TG_PROFILE" 
  BEFORE INSERT ON PROFILE_LANGUAGES
  FOR EACH ROW
BEGIN
  SELECT
   ID.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
ALTER TRIGGER "TG_PROFILE" ENABLE;
--------------------------------------------------------
--  Constraints for Table PROFILE_LANGUAGES
--------------------------------------------------------

  ALTER TABLE "PROFILE_LANGUAGES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROFILE_LANGUAGES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
